spring:
  datasource:
    url: jdbc-secretsmanager:mysql://pinky-database-1.cinfnynhwodi.ap-northeast-2.rds.amazonaws.com:3306/pinkyworldDB
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerMySQLDriver
    username: dev/secrets-manager-rds/mysql
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true